"""empty message

Revision ID: 74c320640ac6
Revises: 05138ff6ffc1
Create Date: 2025-02-17 13:44:11.220803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c320640ac6'
down_revision = '05138ff6ffc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Priority', sa.String(length=50), nullable=True))
        batch_op.drop_column('Priority')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Priority', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('Priority')

    # ### end Alembic commands ###
